resources:
- repo: self

queue:
  name: Hosted
  
steps:
- script: |
    megatools-1.10.2-win64\megadl.exe 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
    DIR 
  displayName: 'Command Line Script'

# - task: FtpUpload@1
#   displayName: 'FTP Upload: aria2_torrent_ftp_vsts_repository'
#   inputs:
#     credentialsOption: inputs

#     serverUrl: 'ftp://192.254.233.216'

#     username: 'root@alaneesgroup.com'

#     password: 9895204814

#     rootDirectory: 'aria2_torrent_ftp_vsts_repository'

#     remoteDirectory: '/aria2_torrent_ftp_vsts_repository'