# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    mkdir megadl_ftp_vsts_repository
    megatools-1.10.2-win64\megadl.exe --path megadl_ftp_vsts_repository 'https://mega.nz/#F!aTxAmKaS!VnaKFs0a8uQNDV6owLq3TA'
    DIR megadl_ftp_vsts_repository
  displayName: 'megatools dl'
  timeoutInMinutes: 0
