# megadl pipeline

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    mkdir megadl_ftp_vsts_repository
    megatools-1.10.2-win64\megadl.exe --path megadl_ftp_vsts_repository https://mega.nz/#F!aTxAmKaS!VnaKFs0a8uQNDV6owLq3TA
    DIR megadl_ftp_vsts_repository
  displayName: 'megatools dl'
  timeoutInMinutes: 0

# Upload Folder
- task: FtpUpload@1
  displayName: 'FTP Folder'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://192.254.233.216'
    username: 'root@alaneesgroup.com'
    password: 9895204814
    rootDirectory: 'megadl_ftp_vsts_repository'
    remoteDirectory: '/azure_devops/megadl'